### ISSUE TITLE
remove role="button"

### ISSUE THREAD

**Issue by dreamwhisper** [copyblogger/responsive-menus#3]
So we started off by having role="button" in the old version, I believe because it was included in third party scripts. It carried through to this script. I mentioned it before, but it slipped through. 

It isn't necessary to have role="button" on a button. It is a button by nature. :)

It gets reported as an error in various testing tools.
https://tenon.io/testNow.php?url=http://demo.studiopress.com/genesis-sample/

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_button_role

I don't think it has any real negative impact, but we should consider removing it.

**Comment by cjkoepke** [comment]
@dreamwhisper Since the `role` attribute has been removed, I'm going to close this issue. Feel free to reopen if you feel there are still issues to discuss.
